"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_template_access import DeviceTemplateAccess
from python_msx_sdk.model.template_parameter_validator import TemplateParameterValidator
globals()['DeviceTemplateAccess'] = DeviceTemplateAccess
globals()['TemplateParameterValidator'] = TemplateParameterValidator
from python_msx_sdk.model.device_template_create import DeviceTemplateCreate


class TestDeviceTemplateCreate(unittest.TestCase):
    """DeviceTemplateCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceTemplateCreate(self):
        """Test DeviceTemplateCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceTemplateCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
