"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.page_header import PageHeader
from python_msx_sdk.model.site import Site
from python_msx_sdk.model.sites_page_all_of import SitesPageAllOf
globals()['PageHeader'] = PageHeader
globals()['Site'] = Site
globals()['SitesPageAllOf'] = SitesPageAllOf
from python_msx_sdk.model.sites_page import SitesPage


class TestSitesPage(unittest.TestCase):
    """SitesPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSitesPage(self):
        """Test SitesPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SitesPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
