"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.site_create_all_of import SiteCreateAllOf


class TestSiteCreateAllOf(unittest.TestCase):
    """SiteCreateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteCreateAllOf(self):
        """Test SiteCreateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SiteCreateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
