"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.site_location import SiteLocation


class TestSiteLocation(unittest.TestCase):
    """SiteLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteLocation(self):
        """Test SiteLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SiteLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
