"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.template_parameter_validator import TemplateParameterValidator
globals()['TemplateParameterValidator'] = TemplateParameterValidator
from python_msx_sdk.model.device_template_version_create import DeviceTemplateVersionCreate


class TestDeviceTemplateVersionCreate(unittest.TestCase):
    """DeviceTemplateVersionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceTemplateVersionCreate(self):
        """Test DeviceTemplateVersionCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceTemplateVersionCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
