"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import unittest

import python_msx_sdk
from python_msx_sdk.api.workflows_api import WorkflowsApi  # noqa: E501


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self):
        self.api = WorkflowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_workflow(self):
        """Test case for delete_workflow

        Delete a workflow.  # noqa: E501
        """
        pass

    def test_export_workflow(self):
        """Test case for export_workflow

        Exports a workflow.  # noqa: E501
        """
        pass

    def test_get_workflow(self):
        """Test case for get_workflow

        Returns a workflow.  # noqa: E501
        """
        pass

    def test_get_workflow_start_config(self):
        """Test case for get_workflow_start_config

        Returns a workflow start config.  # noqa: E501
        """
        pass

    def test_get_workflows_list(self):
        """Test case for get_workflows_list

        Returns a list of workflows.  # noqa: E501
        """
        pass

    def test_import_workflow(self):
        """Test case for import_workflow

        Imports a workflow.  # noqa: E501
        """
        pass

    def test_start_workflow(self):
        """Test case for start_workflow

        Starts a workflow.  # noqa: E501
        """
        pass

    def test_update_workflow(self):
        """Test case for update_workflow

        Updates a workflow.  # noqa: E501
        """
        pass

    def test_validate_workflow(self):
        """Test case for validate_workflow

        Validates a workflow.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
