"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import unittest

import python_msx_sdk
from python_msx_sdk.api.billing_prices_api import BillingPricesApi  # noqa: E501


class TestBillingPricesApi(unittest.TestCase):
    """BillingPricesApi unit test stubs"""

    def setUp(self):
        self.api = BillingPricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_price(self):
        """Test case for add_price

        Add price for tenant and event type.  # noqa: E501
        """
        pass

    def test_delete_price(self):
        """Test case for delete_price

        Delete a price.  # noqa: E501
        """
        pass

    def test_get_price(self):
        """Test case for get_price

        Get a price.  # noqa: E501
        """
        pass

    def test_get_prices_page(self):
        """Test case for get_prices_page

        Retrieve a page of prices.  # noqa: E501
        """
        pass

    def test_update_price(self):
        """Test case for update_price

        Update price for an event type and tenant.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
