"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.workflow_event_update import WorkflowEventUpdate
globals()['WorkflowEventUpdate'] = WorkflowEventUpdate
from python_msx_sdk.model.workflow_event_create import WorkflowEventCreate


class TestWorkflowEventCreate(unittest.TestCase):
    """WorkflowEventCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowEventCreate(self):
        """Test WorkflowEventCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowEventCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
