"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.product import Product
globals()['Product'] = Product
from python_msx_sdk.model.products_page_all_of import ProductsPageAllOf


class TestProductsPageAllOf(unittest.TestCase):
    """ProductsPageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductsPageAllOf(self):
        """Test ProductsPageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductsPageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
