"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.change_request_update import ChangeRequestUpdate
globals()['ChangeRequestUpdate'] = ChangeRequestUpdate
from python_msx_sdk.model.change_request_create import ChangeRequestCreate


class TestChangeRequestCreate(unittest.TestCase):
    """ChangeRequestCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeRequestCreate(self):
        """Test ChangeRequestCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeRequestCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
