"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.page_header import PageHeader
from python_msx_sdk.model.template_application import TemplateApplication
from python_msx_sdk.model.template_applications_page_all_of import TemplateApplicationsPageAllOf
globals()['PageHeader'] = PageHeader
globals()['TemplateApplication'] = TemplateApplication
globals()['TemplateApplicationsPageAllOf'] = TemplateApplicationsPageAllOf
from python_msx_sdk.model.template_applications_page import TemplateApplicationsPage


class TestTemplateApplicationsPage(unittest.TestCase):
    """TemplateApplicationsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplateApplicationsPage(self):
        """Test TemplateApplicationsPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TemplateApplicationsPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
