"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_template_update_details import DeviceTemplateUpdateDetails
globals()['DeviceTemplateUpdateDetails'] = DeviceTemplateUpdateDetails
from python_msx_sdk.model.device_template_update_request import DeviceTemplateUpdateRequest


class TestDeviceTemplateUpdateRequest(unittest.TestCase):
    """DeviceTemplateUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceTemplateUpdateRequest(self):
        """Test DeviceTemplateUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceTemplateUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
