"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.workflow_schema import WorkflowSchema
globals()['WorkflowSchema'] = WorkflowSchema
from python_msx_sdk.model.workflow_schema_by_type_response import WorkflowSchemaByTypeResponse


class TestWorkflowSchemaByTypeResponse(unittest.TestCase):
    """WorkflowSchemaByTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowSchemaByTypeResponse(self):
        """Test WorkflowSchemaByTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowSchemaByTypeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
