"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_compliance_state import DeviceComplianceState


class TestDeviceComplianceState(unittest.TestCase):
    """DeviceComplianceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceComplianceState(self):
        """Test DeviceComplianceState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceComplianceState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
