"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.template_assignment_all_of import TemplateAssignmentAllOf
from python_msx_sdk.model.template_status import TemplateStatus
from python_msx_sdk.model.template_status_meta import TemplateStatusMeta
globals()['TemplateAssignmentAllOf'] = TemplateAssignmentAllOf
globals()['TemplateStatus'] = TemplateStatus
globals()['TemplateStatusMeta'] = TemplateStatusMeta
from python_msx_sdk.model.template_assignment import TemplateAssignment


class TestTemplateAssignment(unittest.TestCase):
    """TemplateAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplateAssignment(self):
        """Test TemplateAssignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TemplateAssignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
