"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.workflow_category_update import WorkflowCategoryUpdate


class TestWorkflowCategoryUpdate(unittest.TestCase):
    """WorkflowCategoryUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowCategoryUpdate(self):
        """Test WorkflowCategoryUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowCategoryUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
