"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.incident_update import IncidentUpdate
globals()['IncidentUpdate'] = IncidentUpdate
from python_msx_sdk.model.incident_create import IncidentCreate


class TestIncidentCreate(unittest.TestCase):
    """IncidentCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncidentCreate(self):
        """Test IncidentCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncidentCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
