"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


import unittest

import python_msx_sdk
from python_msx_sdk.api.licensing_configurations_api import LicensingConfigurationsApi  # noqa: E501


class TestLicensingConfigurationsApi(unittest.TestCase):
    """LicensingConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = LicensingConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_smart_account_configuration(self):
        """Test case for create_smart_account_configuration

        Creates a smart account configuration.  # noqa: E501
        """
        pass

    def test_get_smart_account_configuration(self):
        """Test case for get_smart_account_configuration

        Returns a smart account configuration.  # noqa: E501
        """
        pass

    def test_update_smart_account_configuration(self):
        """Test case for update_smart_account_configuration

        Updates a smart account configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
