/*
 * MSX SDK
 *
 * MSX SDK client.
 *
 * API version: 1.0.9
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msxsdk

import (
	"encoding/json"
)

// BillingCyclesPageAllOf struct for BillingCyclesPageAllOf
type BillingCyclesPageAllOf struct {
	Contents *[]BillingCycle `json:"contents,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BillingCyclesPageAllOf BillingCyclesPageAllOf

// NewBillingCyclesPageAllOf instantiates a new BillingCyclesPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingCyclesPageAllOf() *BillingCyclesPageAllOf {
	this := BillingCyclesPageAllOf{}
	return &this
}

// NewBillingCyclesPageAllOfWithDefaults instantiates a new BillingCyclesPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingCyclesPageAllOfWithDefaults() *BillingCyclesPageAllOf {
	this := BillingCyclesPageAllOf{}
	return &this
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *BillingCyclesPageAllOf) GetContents() []BillingCycle {
	if o == nil || o.Contents == nil {
		var ret []BillingCycle
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCyclesPageAllOf) GetContentsOk() (*[]BillingCycle, bool) {
	if o == nil || o.Contents == nil {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *BillingCyclesPageAllOf) HasContents() bool {
	if o != nil && o.Contents != nil {
		return true
	}

	return false
}

// SetContents gets a reference to the given []BillingCycle and assigns it to the Contents field.
func (o *BillingCyclesPageAllOf) SetContents(v []BillingCycle) {
	o.Contents = &v
}

func (o BillingCyclesPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Contents != nil {
		toSerialize["contents"] = o.Contents
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BillingCyclesPageAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varBillingCyclesPageAllOf := _BillingCyclesPageAllOf{}

	if err = json.Unmarshal(bytes, &varBillingCyclesPageAllOf); err == nil {
		*o = BillingCyclesPageAllOf(varBillingCyclesPageAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "contents")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBillingCyclesPageAllOf struct {
	value *BillingCyclesPageAllOf
	isSet bool
}

func (v NullableBillingCyclesPageAllOf) Get() *BillingCyclesPageAllOf {
	return v.value
}

func (v *NullableBillingCyclesPageAllOf) Set(val *BillingCyclesPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingCyclesPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingCyclesPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingCyclesPageAllOf(val *BillingCyclesPageAllOf) *NullableBillingCyclesPageAllOf {
	return &NullableBillingCyclesPageAllOf{value: val, isSet: true}
}

func (v NullableBillingCyclesPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingCyclesPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


