/*
 * MSX SDK
 *
 * MSX SDK client.
 *
 * API version: 1.0.9
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msxsdk

import (
	"encoding/json"
)

// ServiceNowConfigurationsPageAllOf struct for ServiceNowConfigurationsPageAllOf
type ServiceNowConfigurationsPageAllOf struct {
	Contents *[]ServiceNowConfiguration `json:"contents,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceNowConfigurationsPageAllOf ServiceNowConfigurationsPageAllOf

// NewServiceNowConfigurationsPageAllOf instantiates a new ServiceNowConfigurationsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceNowConfigurationsPageAllOf() *ServiceNowConfigurationsPageAllOf {
	this := ServiceNowConfigurationsPageAllOf{}
	return &this
}

// NewServiceNowConfigurationsPageAllOfWithDefaults instantiates a new ServiceNowConfigurationsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceNowConfigurationsPageAllOfWithDefaults() *ServiceNowConfigurationsPageAllOf {
	this := ServiceNowConfigurationsPageAllOf{}
	return &this
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *ServiceNowConfigurationsPageAllOf) GetContents() []ServiceNowConfiguration {
	if o == nil || o.Contents == nil {
		var ret []ServiceNowConfiguration
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNowConfigurationsPageAllOf) GetContentsOk() (*[]ServiceNowConfiguration, bool) {
	if o == nil || o.Contents == nil {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *ServiceNowConfigurationsPageAllOf) HasContents() bool {
	if o != nil && o.Contents != nil {
		return true
	}

	return false
}

// SetContents gets a reference to the given []ServiceNowConfiguration and assigns it to the Contents field.
func (o *ServiceNowConfigurationsPageAllOf) SetContents(v []ServiceNowConfiguration) {
	o.Contents = &v
}

func (o ServiceNowConfigurationsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Contents != nil {
		toSerialize["contents"] = o.Contents
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServiceNowConfigurationsPageAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varServiceNowConfigurationsPageAllOf := _ServiceNowConfigurationsPageAllOf{}

	if err = json.Unmarshal(bytes, &varServiceNowConfigurationsPageAllOf); err == nil {
		*o = ServiceNowConfigurationsPageAllOf(varServiceNowConfigurationsPageAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "contents")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceNowConfigurationsPageAllOf struct {
	value *ServiceNowConfigurationsPageAllOf
	isSet bool
}

func (v NullableServiceNowConfigurationsPageAllOf) Get() *ServiceNowConfigurationsPageAllOf {
	return v.value
}

func (v *NullableServiceNowConfigurationsPageAllOf) Set(val *ServiceNowConfigurationsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceNowConfigurationsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceNowConfigurationsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceNowConfigurationsPageAllOf(val *ServiceNowConfigurationsPageAllOf) *NullableServiceNowConfigurationsPageAllOf {
	return &NullableServiceNowConfigurationsPageAllOf{value: val, isSet: true}
}

func (v NullableServiceNowConfigurationsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceNowConfigurationsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


