/*
 * MSX SDK
 *
 * MSX SDK client.
 *
 * API version: 1.0.9
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msxsdk

import (
	"encoding/json"
)

// TemplateAssignmentsPageAllOf struct for TemplateAssignmentsPageAllOf
type TemplateAssignmentsPageAllOf struct {
	Contents *[]TemplateAssignment `json:"contents,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TemplateAssignmentsPageAllOf TemplateAssignmentsPageAllOf

// NewTemplateAssignmentsPageAllOf instantiates a new TemplateAssignmentsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateAssignmentsPageAllOf() *TemplateAssignmentsPageAllOf {
	this := TemplateAssignmentsPageAllOf{}
	return &this
}

// NewTemplateAssignmentsPageAllOfWithDefaults instantiates a new TemplateAssignmentsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateAssignmentsPageAllOfWithDefaults() *TemplateAssignmentsPageAllOf {
	this := TemplateAssignmentsPageAllOf{}
	return &this
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *TemplateAssignmentsPageAllOf) GetContents() []TemplateAssignment {
	if o == nil || o.Contents == nil {
		var ret []TemplateAssignment
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateAssignmentsPageAllOf) GetContentsOk() (*[]TemplateAssignment, bool) {
	if o == nil || o.Contents == nil {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *TemplateAssignmentsPageAllOf) HasContents() bool {
	if o != nil && o.Contents != nil {
		return true
	}

	return false
}

// SetContents gets a reference to the given []TemplateAssignment and assigns it to the Contents field.
func (o *TemplateAssignmentsPageAllOf) SetContents(v []TemplateAssignment) {
	o.Contents = &v
}

func (o TemplateAssignmentsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Contents != nil {
		toSerialize["contents"] = o.Contents
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TemplateAssignmentsPageAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varTemplateAssignmentsPageAllOf := _TemplateAssignmentsPageAllOf{}

	if err = json.Unmarshal(bytes, &varTemplateAssignmentsPageAllOf); err == nil {
		*o = TemplateAssignmentsPageAllOf(varTemplateAssignmentsPageAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "contents")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplateAssignmentsPageAllOf struct {
	value *TemplateAssignmentsPageAllOf
	isSet bool
}

func (v NullableTemplateAssignmentsPageAllOf) Get() *TemplateAssignmentsPageAllOf {
	return v.value
}

func (v *NullableTemplateAssignmentsPageAllOf) Set(val *TemplateAssignmentsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateAssignmentsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateAssignmentsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateAssignmentsPageAllOf(val *TemplateAssignmentsPageAllOf) *NullableTemplateAssignmentsPageAllOf {
	return &NullableTemplateAssignmentsPageAllOf{value: val, isSet: true}
}

func (v NullableTemplateAssignmentsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateAssignmentsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


