/*
 * MSX SDK
 *
 * MSX SDK client.
 *
 * API version: 1.0.9
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msxsdk

import (
	"encoding/json"
)

// VulnerabilitiesPage struct for VulnerabilitiesPage
type VulnerabilitiesPage struct {
	Page int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	TotalItems NullableInt64 `json:"totalItems,omitempty"`
	HasNext NullableBool `json:"hasNext"`
	HasPrevious NullableBool `json:"hasPrevious"`
	SortBy NullableString `json:"sortBy,omitempty"`
	SortOrder NullableString `json:"sortOrder,omitempty"`
	Contents []Vulnerability `json:"contents"`
	AdditionalProperties map[string]interface{}
}

type _VulnerabilitiesPage VulnerabilitiesPage

// NewVulnerabilitiesPage instantiates a new VulnerabilitiesPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVulnerabilitiesPage(page int32, pageSize int32, hasNext NullableBool, hasPrevious NullableBool, contents []Vulnerability) *VulnerabilitiesPage {
	this := VulnerabilitiesPage{}
	this.Page = page
	this.PageSize = pageSize
	this.HasNext = hasNext
	this.HasPrevious = hasPrevious
	this.Contents = contents
	return &this
}

// NewVulnerabilitiesPageWithDefaults instantiates a new VulnerabilitiesPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVulnerabilitiesPageWithDefaults() *VulnerabilitiesPage {
	this := VulnerabilitiesPage{}
	return &this
}

// GetPage returns the Page field value
func (o *VulnerabilitiesPage) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *VulnerabilitiesPage) GetPageOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *VulnerabilitiesPage) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *VulnerabilitiesPage) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *VulnerabilitiesPage) GetPageSizeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *VulnerabilitiesPage) SetPageSize(v int32) {
	o.PageSize = v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VulnerabilitiesPage) GetTotalItems() int64 {
	if o == nil || o.TotalItems.Get() == nil {
		var ret int64
		return ret
	}
	return *o.TotalItems.Get()
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VulnerabilitiesPage) GetTotalItemsOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.TotalItems.Get(), o.TotalItems.IsSet()
}

// HasTotalItems returns a boolean if a field has been set.
func (o *VulnerabilitiesPage) HasTotalItems() bool {
	if o != nil && o.TotalItems.IsSet() {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given NullableInt64 and assigns it to the TotalItems field.
func (o *VulnerabilitiesPage) SetTotalItems(v int64) {
	o.TotalItems.Set(&v)
}
// SetTotalItemsNil sets the value for TotalItems to be an explicit nil
func (o *VulnerabilitiesPage) SetTotalItemsNil() {
	o.TotalItems.Set(nil)
}

// UnsetTotalItems ensures that no value is present for TotalItems, not even an explicit nil
func (o *VulnerabilitiesPage) UnsetTotalItems() {
	o.TotalItems.Unset()
}

// GetHasNext returns the HasNext field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *VulnerabilitiesPage) GetHasNext() bool {
	if o == nil || o.HasNext.Get() == nil {
		var ret bool
		return ret
	}

	return *o.HasNext.Get()
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VulnerabilitiesPage) GetHasNextOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.HasNext.Get(), o.HasNext.IsSet()
}

// SetHasNext sets field value
func (o *VulnerabilitiesPage) SetHasNext(v bool) {
	o.HasNext.Set(&v)
}

// GetHasPrevious returns the HasPrevious field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *VulnerabilitiesPage) GetHasPrevious() bool {
	if o == nil || o.HasPrevious.Get() == nil {
		var ret bool
		return ret
	}

	return *o.HasPrevious.Get()
}

// GetHasPreviousOk returns a tuple with the HasPrevious field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VulnerabilitiesPage) GetHasPreviousOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.HasPrevious.Get(), o.HasPrevious.IsSet()
}

// SetHasPrevious sets field value
func (o *VulnerabilitiesPage) SetHasPrevious(v bool) {
	o.HasPrevious.Set(&v)
}

// GetSortBy returns the SortBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VulnerabilitiesPage) GetSortBy() string {
	if o == nil || o.SortBy.Get() == nil {
		var ret string
		return ret
	}
	return *o.SortBy.Get()
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VulnerabilitiesPage) GetSortByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SortBy.Get(), o.SortBy.IsSet()
}

// HasSortBy returns a boolean if a field has been set.
func (o *VulnerabilitiesPage) HasSortBy() bool {
	if o != nil && o.SortBy.IsSet() {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given NullableString and assigns it to the SortBy field.
func (o *VulnerabilitiesPage) SetSortBy(v string) {
	o.SortBy.Set(&v)
}
// SetSortByNil sets the value for SortBy to be an explicit nil
func (o *VulnerabilitiesPage) SetSortByNil() {
	o.SortBy.Set(nil)
}

// UnsetSortBy ensures that no value is present for SortBy, not even an explicit nil
func (o *VulnerabilitiesPage) UnsetSortBy() {
	o.SortBy.Unset()
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VulnerabilitiesPage) GetSortOrder() string {
	if o == nil || o.SortOrder.Get() == nil {
		var ret string
		return ret
	}
	return *o.SortOrder.Get()
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VulnerabilitiesPage) GetSortOrderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SortOrder.Get(), o.SortOrder.IsSet()
}

// HasSortOrder returns a boolean if a field has been set.
func (o *VulnerabilitiesPage) HasSortOrder() bool {
	if o != nil && o.SortOrder.IsSet() {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given NullableString and assigns it to the SortOrder field.
func (o *VulnerabilitiesPage) SetSortOrder(v string) {
	o.SortOrder.Set(&v)
}
// SetSortOrderNil sets the value for SortOrder to be an explicit nil
func (o *VulnerabilitiesPage) SetSortOrderNil() {
	o.SortOrder.Set(nil)
}

// UnsetSortOrder ensures that no value is present for SortOrder, not even an explicit nil
func (o *VulnerabilitiesPage) UnsetSortOrder() {
	o.SortOrder.Unset()
}

// GetContents returns the Contents field value
func (o *VulnerabilitiesPage) GetContents() []Vulnerability {
	if o == nil {
		var ret []Vulnerability
		return ret
	}

	return o.Contents
}

// GetContentsOk returns a tuple with the Contents field value
// and a boolean to check if the value has been set.
func (o *VulnerabilitiesPage) GetContentsOk() (*[]Vulnerability, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Contents, true
}

// SetContents sets field value
func (o *VulnerabilitiesPage) SetContents(v []Vulnerability) {
	o.Contents = v
}

func (o VulnerabilitiesPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["pageSize"] = o.PageSize
	}
	if o.TotalItems.IsSet() {
		toSerialize["totalItems"] = o.TotalItems.Get()
	}
	if true {
		toSerialize["hasNext"] = o.HasNext.Get()
	}
	if true {
		toSerialize["hasPrevious"] = o.HasPrevious.Get()
	}
	if o.SortBy.IsSet() {
		toSerialize["sortBy"] = o.SortBy.Get()
	}
	if o.SortOrder.IsSet() {
		toSerialize["sortOrder"] = o.SortOrder.Get()
	}
	if true {
		toSerialize["contents"] = o.Contents
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *VulnerabilitiesPage) UnmarshalJSON(bytes []byte) (err error) {
	varVulnerabilitiesPage := _VulnerabilitiesPage{}

	if err = json.Unmarshal(bytes, &varVulnerabilitiesPage); err == nil {
		*o = VulnerabilitiesPage(varVulnerabilitiesPage)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "totalItems")
		delete(additionalProperties, "hasNext")
		delete(additionalProperties, "hasPrevious")
		delete(additionalProperties, "sortBy")
		delete(additionalProperties, "sortOrder")
		delete(additionalProperties, "contents")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVulnerabilitiesPage struct {
	value *VulnerabilitiesPage
	isSet bool
}

func (v NullableVulnerabilitiesPage) Get() *VulnerabilitiesPage {
	return v.value
}

func (v *NullableVulnerabilitiesPage) Set(val *VulnerabilitiesPage) {
	v.value = val
	v.isSet = true
}

func (v NullableVulnerabilitiesPage) IsSet() bool {
	return v.isSet
}

func (v *NullableVulnerabilitiesPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVulnerabilitiesPage(val *VulnerabilitiesPage) *NullableVulnerabilitiesPage {
	return &NullableVulnerabilitiesPage{value: val, isSet: true}
}

func (v NullableVulnerabilitiesPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVulnerabilitiesPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


